name: mindconnect

services:
  frontend:
    build:
      context: ./frontend
      dockerfile: Dockerfile
    container_name: mindconnect-frontend
    ports:
      - "3000:3000"
    environment:
      - NODE_ENV=production
      - API_BASE_URL=http://backend:8080/api/v1
      - NEXT_PUBLIC_API_BASE_URL=http://localhost:8080/api/v1
    depends_on:
      backend:
        condition: service_healthy
    networks:
      - mindconnect-network
    restart: unless-stopped

  backend:
    build:
      context: ./backend
      dockerfile: Dockerfile
    container_name: mindconnect-backend
    ports:
      - "8080:8080"
    environment:
      - NODE_ENV=development
      - PORT=8080
      - HOST=0.0.0.0
      - DATABASE_URL=mysql://mindconnect_user:mindconnect_pass@mysql:3306/mindconnect
      - REDIS_URL=redis://redis:6379
      - JWT_SECRET=dev_jwt_secret_change_in_production
      - CORS_ORIGIN=http://localhost:3000
    depends_on:
      mysql:
        condition: service_healthy
      redis:
        condition: service_started
    networks:
      - mindconnect-network
    restart: unless-stopped
    healthcheck:
      test: ["CMD", "curl", "-f", "http://localhost:8080/health"]
      interval: 30s
      timeout: 10s
      retries: 3
      start_period: 40s

  mysql:
    image: mysql:8.0
    container_name: mindconnect-mysql
    environment:
      - MYSQL_ROOT_PASSWORD=root_password_change_me
      - MYSQL_DATABASE=mindconnect
      - MYSQL_USER=mindconnect_user
      - MYSQL_PASSWORD=mindconnect_pass
    ports:
      - "3307:3306"
    volumes:
      - mysql_data:/var/lib/mysql
    networks:
      - mindconnect-network
    restart: unless-stopped
    healthcheck:
      test: ["CMD", "mysqladmin", "ping", "-h", "localhost", "-u", "root", "-proot_password_change_me"]
      interval: 10s
      timeout: 5s
      retries: 5
      start_period: 30s

  redis:
    image: redis:7-alpine
    container_name: mindconnect-redis
    ports:
      - "6380:6379"
    volumes:
      - redis_data:/data
    networks:
      - mindconnect-network
    restart: unless-stopped
    command: redis-server --appendonly yes
    healthcheck:
      test: ["CMD", "redis-cli", "ping"]
      interval: 10s
      timeout: 5s
      retries: 5

networks:
  mindconnect-network:
    driver: bridge

volumes:
  mysql_data:
  redis_data:
